name: 'Setup JWasm'
description: 'Install JWasm'
runs:
  using: 'composite'
  steps:
    - if: ${{ runner.os == 'Linux' || runner.os == 'Windows' }}
      uses: karcherm/action-install-jw@v1.0
      with:
        jwasm: true
    - if: ${{ runner.os == 'macOS' }}
      run: brew install jwasm
      shell: bash
